Vagrant.configure("2") do |cf|
  # NFS Server
    
    cf.vm.provider "hyperv" do |hv|
      hv.cpus = "5"
      hv.vmname = "nfs"
      hv.maxmemory = 4096
      hv.memory = 4096
    end
    
    cf.vm.define "nfs-server" do |nfs|
      cf.vm.box = "generic/ubuntu2004"
      cf.vm.provision "shell",path: "bootstrap_nfs.sh"
    end
 
end